name: Integracion Continua (CI)

on:
  push:
    branches: [ main ]

jobs:
  pruebas:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar pruebas automatizadas
      run: |
        python -m pytest

    # Feedback
    - name: Notificar a Discord
      if: always()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          curl -H "Content-Type: application/json" -d '{"content": "✅ **¡Éxito!** Las pruebas del Contador de Visitas pasaron correctamente. El código se está enviando a producción."}' $DISCORD_WEBHOOK
        else
          curl -H "Content-Type: application/json" -d '{"content": "❌ **¡Alerta!** Alguien rompió el código. Las pruebas de Integración Continua fallaron."}' $DISCORD_WEBHOOK
        fi